spring:
  profiles:
    active: h2
  application:
    name: hotels-service
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8092
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html