spring:
  profiles:
    active: h2
  application:
    name: hotels-service
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8092
